name = "VPopMIP"
uuid = "7eca7bcc-9451-40d0-a897-5ef4a75126a7"
authors = ["Evgeny Metelkin metelkin@insysbio.com", "Ivan Borisov borisov@insysbio.com"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DigiPopData = "0d51003c-419e-4b70-b590-68fae1e54ab3"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.8.1"
DigiPopData = "0.1.0"
JuMP = "1.29.3"
MathOptInterface = "1.48.0"
RecipesBase = "1.3.4"
Reexport = "1.2.2"
SCIP = "0.12.7"
StatsBase = "0.34.10"
julia = "1.10"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames"]
